type localStorage
{
    kanjilist: {
        [kanji]:int
    },

    [words]: kanjidata
}

type kanjidata
{
    maindata:[
        string, #kanji
        string, #hiragana
        string  #definition string
    ],

    rubys:[[
        rubyposition:int,ruby:string
    ]]!
}